#!/bin/bash

# Builds a project based on a manifest file.

set -e

function build {
    if ! [ -f "$manifest" ]
    then
        echo "Error: Manifest not found $manifest" >&2
        exit 1
    fi
    
    package_folder="`mktemp --directory \".package_${manifest##*/}_XXX\"`"
    # From this point forward we need to delet the temp folder if anything fails.
    trap 'x=$? ; chmod -R u+w "$package_folder" ; rm -rf "$package_folder"; exit $x' INT TERM EXIT
    echo "Assembling pacakge in `pwd`/$package_folder"

    mkdir --mode 755 "$package_folder/DEBIAN"
    printf '%-10s%-40s%-60s%-5s\n' Action 'Surce File' 'Target File' 'File Mode'
    while read action source_file target_file file_mode
    do
        target_file="${target_file#/}"
       	if [ -n "$file_mode" ] 
		then 
            dirmode="$(( 
                  ( ( ( $file_mode % 10 & 4 ) / 4 | ($file_mode % 10) ) ) 
                + ( ( ( $file_mode / 10 % 10 & 4 ) / 4 | ($file_mode / 10 % 10) ) * 10 ) 
                + ( ( ( $file_mode / 100 & 4 ) / 4 | ($file_mode / 100) ) * 100) 
                ))"
		else
			dirmode=""
		fi

        if [ "$action" = 'file' ]
        then
			printf '%-10s%-40s/%-60s%-5s\n' "$action" "$source_file" "$target_file" "$file_mode"
			prep_source
			prep_target
            copy_file
        elif [ "$action" = 'link' ]
        then
			printf '%-10s%-40s/%s --> %s\n' "$action" "" "$target_file" "$source_file"
            prep_target
            create_link
        elif [ "$action" = 'dir' ]
        then
			file_mode="$target_file"
			target_file="${source_file#/}"
            unset source_file
			printf '%-10s%-40s/%-60s%-5s\n' "$action" "$source_file" "$target_file" "$file_mode"
            prep_target
            create_dir
        elif [ "$action" = 'control' ]
        then
			printf '%-10s%-40s/%-60s%-5s\n' "$action" "$source_file" DEBIAN/control 644
            prep_source
            create_control
        elif [ "$action" = 'source' ]
        then
			printf '%-10s%-40s\n' "$action" "$source_file"
            change_source "$source_file"
        else 
            echo "Error: unknown action $action" >&2
            exit 1
        fi 
    done < <(grep -v '^[ \t]*#\|^[ \t]*$' "$manifest")

    (
        cd "$package_folder" ; 
        for file in * 
        do
            if [ "$file" != DEBIAN ]
            then
                find "$file" -type f -exec md5sum  '{}' '+' >> DEBIAN/md5sums
            fi
        done
    )

    size=`find "$package_folder" -type f -exec ls -l  '{}' ';' | awk 'BEGIN {x=0} {x=x+$5} END {print int(x/1024)}'`
    echo "Installed-Size: $size" >> "$package_folder/DEBIAN/control"

    chmod 555 "$package_folder/DEBIAN/control"

    find "$package_folder" -name .svn -exec rm -rf {} +

    fakeroot dpkg-deb --build "$package_folder" .

}

function prep_source {
    if [ -z "$source_folder" ]
    then
        echo "Warning: No source specified" >&2
        change_source .
    fi	
}

function prep_target {
    if [ -e "$package_folder/$target_file" ]
    then
        echo "Error: file already exists $package_folder/$target_file" >&2
        exit 1
    fi

    parent_dir=`dirname "$package_folder/$target_file"`
    if [ -n "$dirmode" ]
    then
        mkdir --parents --mode $dirmode `dirname "$package_folder/$target_file"`
    else
        mkdir --parents $dirmode `dirname "$package_folder/$target_file"`
    fi
}

function change_source {
    source_folder=`dirname "$manifest"`/"$1"
    source_folder=`readlink -m "$source_folder"`
    echo "$source_folder"
}

function copy_file {
    cp -r "$source_folder/$source_file" "$package_folder/$target_file"
    if [ -n "$file_mode" ]
    then      
        find "$package_folder/$target_file" -type f -exec chmod "$file_mode" '{}' +
        find "$package_folder/$target_file" -type d -exec chmod "$dirmode"   '{}' +
    fi
}

function create_link {
    ln -s "$source_file" "$package_folder/$target_file"
}

function create_dir {
    if [ -n "$file_mode" ]
    then
        mkdir --mode $file_mode "$package_folder/$target_file"
    else
        mkdir "$package_folder/$target_file"
    fi
}

function create_control {
    if [ -e "$package_folder/DEBIAN/control" ]
    then
        echo "Error: file already exists $package_folder/$target_file" >&2
        exit 1
    fi
    version=`git describe --tags --match v[0-9].[0-9]* || true`
    if [ -n "$version" ]
    then
        grep -v '^Version:' "$source_folder/$source_file" | grep -v 'Installed-Size:' > "$package_folder/DEBIAN/control"
        echo "Version: ${version#v}" >> "$package_folder/DEBIAN/control"
    else
        grep -v 'Installed-Size:' "$source_folder/$source_file" > "$package_folder/DEBIAN/control"
    fi
	chmod 644 "$package_folder/DEBIAN/control"
}

for manifest in "$@"
do
    build
done

exit 0
